name: shop
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  delayed_widget: ^1.1.2
  connectivity_plus: ^6.1.0
  loading_animation_widget: ^1.3.0
  smooth_page_indicator: ^1.2.0+3
  shimmer: ^3.0.0
  get_it: ^8.0.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  dio: ^5.7.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_localizations:
    sdk: flutter
  


flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir.ttf

